# Generated by Django 3.2.13 on 2022-12-04 04:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('activity_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('activity_name', models.CharField(max_length=100, unique=True)),
                ('activity_type', models.CharField(max_length=100)),
                ('activity_date', models.DateField()),
                ('activity_time', models.CharField(max_length=100)),
                ('activity_duration', models.CharField(max_length=100)),
                ('label', models.CharField(blank=True, max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('admin_mail', models.CharField(max_length=500, unique=True)),
                ('admin_password', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Statistics',
            fields=[
                ('st_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('st_date', models.DateField()),
                ('st_nb_user', models.IntegerField()),
                ('st_nb_pub', models.IntegerField()),
                ('st_nb_sugg', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('user_mail', models.EmailField(max_length=254, unique=True)),
                ('user_password', models.CharField(max_length=500)),
                ('user_name', models.CharField(max_length=50)),
                ('user_Lastname', models.CharField(max_length=50)),
                ('user_date_birth', models.DateField()),
                ('user_dateOfJoin', models.DateField()),
                ('user_avatar', models.TextField(default='', max_length=10000)),
                ('user_type', models.CharField(blank=True, max_length=40)),
                ('user_num', models.CharField(blank=True, max_length=500)),
                ('user_address', models.CharField(blank=True, max_length=500)),
                ('admin', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='ResetPassword',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('token', models.TextField(max_length=500)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pcd.user')),
            ],
        ),
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('plan_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('plan_name', models.CharField(max_length=100)),
                ('plan_type', models.CharField(max_length=500)),
                ('plan_activity', models.ManyToManyField(related_name='plan_activity', to='pcd.Activity')),
                ('plan_author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pcd.user')),
            ],
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('date', models.DateField(auto_now=True)),
                ('notification', models.TextField(max_length=500)),
                ('is_seen', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pcd.user')),
            ],
        ),
        migrations.CreateModel(
            name='Notes',
            fields=[
                ('note_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('note_content', models.TextField(max_length=2500)),
                ('note_date', models.DateField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pcd.user')),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('message_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('message_content', models.TextField(max_length=500, unique=True)),
                ('message_date', models.DateField(auto_now=True)),
                ('message_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pcd.user')),
            ],
        ),
    ]
