# Generated by Django 3.2.13 on 2022-12-04 05:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pcd', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='plan',
            name='plan_author',
        ),
    ]
