# Generated by Django 3.2.13 on 2022-05-02 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pcd', '0005_resetpassword'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notes',
            name='note_content',
            field=models.TextField(max_length=2500),
        ),
    ]
